name: ospace
description: "OmniSpace app with newer version and everything"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  cached_network_image: ^3.4.1
  any_link_preview: ^3.0.0
  curved_navigation_bar: ^1.0.6
  coingecko_api: ^2.0.1
  logger: ^2.4.0
  shimmer: ^3.0.0
  phosphor_flutter: ^2.1.0
  flutter_inappwebview: ^6.1.5
  share_plus: ^10.1.0
  url_launcher: ^6.3.1
  intl: ^0.19.0
  open_meteo: ^2.0.2
  flutter_launcher_icons: ^0.14.1
  flutter_quill: ^10.8.4
  mockito: ^5.4.4
  device_preview: ^1.2.0
  flutter_login: ^5.0.0
  image_picker: ^1.1.2
  path: ^1.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - 'assets/'
    - 'assets/icons/'
    - 'assets/img.png'

flutter_icons:
  android: true
  ios: true
  image_path: "assets/img.png"
