name: ospace
description: "OmniSpace app with newer version and everything"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  cached_network_image: ^3.4.1
  any_link_preview: ^3.0.0
  curved_navigation_bar: ^1.0.6
  weather_pack: ^1.1.0
  coingecko_api: ^2.0.1
  logger: ^2.4.0
  shimmer: ^3.0.0
  phosphor_flutter: ^2.1.0
  flutter_inappwebview: ^6.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - 'assets/img.png'
